# This file configures the analyzer to pin down dead code, missing consts, and bad practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    avoid_unnecessary_containers: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unawaited_futures: false
